name: Build and Test
on:
  push:
    branches:
      - master

jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout del CÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurar Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar Dependencias
        run: npm ci

      - name: ğŸ§ª Ejecutar Pruebas Automatizadas (Unidad/IntegraciÃ³n)
        run: npm test
      
      - name: ğŸ·ï¸ Crear Tag DinÃ¡mico
        id: set_tag
        run: |
          # ğŸ¯ Se aÃ±ade el nombre del repositorio (github.event.repository.name) 
          REPO_NAME="${{ github.event.repository.name }}"
          TAG_NAME="${REPO_NAME}:${{ github.ref_name }}-${{ github.run_id }}"
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "Tag generado: ${TAG_NAME}"
      
      - name: ğŸ³ Construir Imagen Docker
        run: docker build -t ${TAG_NAME} .