name: Build and Test
on:
  push:
    branches:
      - master

jobs:
  Build_Test:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout del CÃ³digo
        uses: actions/checkout@v4

      - name: âš™ï¸ Configurar Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar Dependencias
        run: npm ci

      - name: ğŸ§ª Ejecutar Pruebas Automatizadas (Unidad/IntegraciÃ³n)
        run: npm test
      
      - name: ğŸ·ï¸ Crear y Exportar Tag DinÃ¡mico
        id: set_tag
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          TAG_FULL="${REPO_NAME,,}:${{ github.ref_name }}-${{ github.run_id }}"
          echo "tag=${TAG_FULL}" >> $GITHUB_OUTPUT 
          echo "Tag generado: ${TAG_FULL}"

      - name: ğŸ³ Construir Imagen Docker
        run: |
          IMAGE_TAG="${{ steps.set_tag.outputs.tag }}"
          docker build -t $IMAGE_TAG .